---
# task file for deploy
    - group:
        name: '{{ application_user }}'
        state: present
      ignore_errors: true

    - name: Add the nginx user to your group
      command: 'usermod -a -G {{ application_user }} nginx'

    - name: Give our user group execute permissions on our home directory
      file:
        path: '{{ user_home }}'
        mode: '0710'

    - name: Change {{ user_home }} permission
      file:
        path: '{{ user_home }}'
        state: directory
        recurse: yes
        owner: '{{ application_user }}'
        group: nginx

    - name: Create transtats.service file
      copy:
        content: |
          [Unit]
          Description=transtats daemon
          Requires=transtats.socket
          After=network.target

          [Service]
          User={{ application_user }}
          Group=nginx
          WorkingDirectory={{ app_home }}
          ExecStart={{ app_home }}/projectenv/bin/gunicorn --workers 3 --bind unix:/run/transtats.sock transtats.wsgi:application
          
          ExecStartPre=+/bin/chown -R {{ application_user }}:{{ application_user }} {{ app_home }}/logs

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/transtats.service

    - name: Create transtats.socket
      copy:
        content: |
          [Unit]
          Description=transtats socket

          [Socket]
          ListenStream=/run/transtats.sock
          # Our service won't need permissions for the socket, since it
          # inherits the file descriptor by socket activation
          # only the nginx daemon will need access to the socket
          User=nginx
          # Optionally restrict the socket permissions even more.
          # Mode=600

          [Install]
          WantedBy=sockets.target
        dest: /etc/systemd/system/transtats.socket

    - name: Set SELinux permissive permanently
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX=(.*)$'
        line: 'SELINUX=permissive'

    - name: Set SELinux permissive
      shell: '/usr/sbin/setenforce 0'

    - name: Start transtats service
      service:
        name: transtats.service
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Start transtats socket
      service:
        name: transtats.socket
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Copy content to nginx.conf 
      blockinfile: 
        path: /etc/nginx/nginx.conf
        insertafter: 'include.*\/etc\/nginx\/conf.d.*'
        content: | 
          server {
                   listen 80;
                   server_name _;

                  location / {
                     proxy_set_header Host $http_host;
                     proxy_set_header X-Real-IP $remote_addr;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                     proxy_set_header X-Forwarded-Proto $scheme;
                     proxy_pass http://unix:/run/transtats.sock;
                     proxy_connect_timeout 300s;
                     proxy_read_timeout 300s;
                  }
                } 

    - name: Add port 80/tcp to firewall
      firewalld:
        port: 80/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - service:
        name: nginx
        enabled: yes
        state: started
