---
# task file db 
    - name: Download .rpm package
      get_url:
        dest: /tmp/epel-release-latest-7.noarch.rpm
        url: '{{ epel_url }}'
        force: no
      when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"   
    
    - name: Uninstall epel package if already installed
      package: 
        name: epel-release.noarch
        state: absent  
      when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"     

    - name: Install Downloaded .rpm package
      package:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"

    - name: Uninstall pgdg package if already install
      package:
        name: pgdg-centos95.noarch
        state: absent
      when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"

    - name: Install pgdg package
      package:
        name: '{{ pgdg_url }}'
        state: present
      when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"

    - name: Update all
      dnf:
        name: '*'
        state: latest

    - name: Ensure packages present
      package:
        name: ' {{ item }} '
        state: latest
      with_items:
        - '{{ db_packages }}'
          
    - name: Stop postgresql service 
      service: 
        name: '{{ pgsql_service }}'
        enabled: yes
        state: stopped

    - name: Delete data directory if exists
      command: 'rm -rf {{ data_dir }}'
      args:
        warn: no
      
    - name: Initialize database
      command: '{{ init_db }}'   

    - name: Change permission of {{ data_dir }}
      file:
        path: '{{ data_dir }}'
        owner: 26
        group: 26
        mode: 0700

    - name: Create pg_hba.conf file
      copy:
        content: | 
          # TYPE  DATABASE        USER            ADDRESS                 METHOD

          # "local" is for Unix domain socket connections only
          local   all             all                                     peer
          # IPv4 local connections:
          #host    all             all             127.0.0.1/32            ident
          host    all             all             {{ groups.transtats | to_json | replace("[", "") | replace("]", "") }}/0            md5
          # IPv6 local connections:
          #host    all             all             ::1/128                 ident
          host    all             all             ::1/128                 md5      
        dest: '{{ data_dir }}pg_hba.conf'      

    - name: Change postgresql listenaddress
      lineinfile:
        path: '{{ data_dir }}postgresql.conf'
        line: listen_addresses = '*'
        insertafter: EOF

    - name: Start postgresql service 
      service: 
        name: '{{ pgsql_service }}'
        enabled: yes
        state: started 

    - name: Alter db user passwd
      command: sudo -u postgres psql -c "ALTER USER {{ db_user }} WITH PASSWORD '{{ db_pass }}';"
      args:
        warn: no

    - name: Create database 
      postgresql_db:
        name: "{{ db_name }}"
        encoding: UTF-8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        template: template0
        login_host: "{{ db_host }}"
        port: 5432
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
