---
- name: Download .rpm package
  get_url:
    dest: /tmp/epel-release-latest-7.noarch.rpm
    url: '{{ epel_url }}'
    force: no
  when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"

- name: Uninstall epel package if already installed
  package:
    name: epel-release.noarch
    state: absent
  when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"

- name: Install Downloaded .rpm package
  package:
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"

- name: Update all
  package:
    name: '*'
    state: latest  

- name: Ensure necessary packages present
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ system_packages }}'


- name: install the 'Development tools' package group
  package:
    name: '@Development tools'
    state: latest
    update_cache: yes


