---
- name: Update all
  package:
    name: '*'
    state: latest  

- name: Ensure necessary packages present
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ system_packages }}'


- name: install the 'Development tools' package group
  package:
    name: '@Development tools'
    state: latest
    update_cache: yes


